/* TP-LINK ARCHER MR200 V1 */

#define BOARD_PID		"TL_MR200-V1"
#define BOARD_NAME		"TL_MR200-V1"
#define BOARD_DESC		"TP-Link Archer MR200 Wireless Router"
#define BOARD_VENDOR_NAME	"TP-LINK Technologies CO., LTD."
#define BOARD_VENDOR_URL	"http://www.tp-link.com/en"
#define BOARD_MODEL_URL		"http://www.tp-link.com/en/download/Archer-MR200_V1.html"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	13
#define BOARD_GPIO_BTN_WPS	9
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_SW2G	72	/* soft led */
#define BOARD_GPIO_LED_SW5G	72	/* soft led */
#define BOARD_GPIO_LED_POWER	12
#define BOARD_GPIO_LED_LAN	1
#define BOARD_GPIO_LED_WAN	14
#undef  BOARD_GPIO_LED_WAN_INVERTED
#define BOARD_GPIO_LED_WAN_PHY	8
#undef  BOARD_GPIO_LED_WAN_PHY_INVERTED
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#define BOARD_GPIO_PWR_USB_ON	1
#define BOARD_GPIO_PWR_USB	11
#undef  BOARD_GPIO_PWR_USB2
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	1
#define BOARD_NUM_ANT_5G_RX	1
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_NUM_ETH_EPHY      4
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
