/* NEXX WT3020A */

#define BOARD_PID		"WT3020A"
#define BOARD_NAME		"WT3020A"
#define BOARD_DESC		"NEXX WT3020A Mobile Router"
#define BOARD_VENDOR_NAME	"NEXX WIRELESS CO., LTD"
#define BOARD_VENDOR_URL	"http://www.nexx.com.cn/"
#define BOARD_MODEL_URL		"http://www.nexx.com.cn/index.php/home/detail?pid=199"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	90
#define BOARD_GPIO_BTN_RESET	1
#undef  BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#define BOARD_GPIO_LED_WIFI	72
#undef  BOARD_GPIO_LED_POWER
#undef  BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_WAN
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_NUM_ETH_EPHY	2
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
