CFILES = hfs_endian.c makehfs.c newfs_hfs.c
OFILES = $(CFILES:.c=.o)

all: newfs_hfs

newfs_hfs: $(OFILES)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OFILES) -lcrypto

clean:
	$(RM) newfs_hfs $(OFILES)

.PHONY : FORCE clean
