/* MQMAKER WITI */

#define BOARD_PID		"MQ-WITI"
#define BOARD_NAME		"MQ-WITI"
#define BOARD_DESC		"MQ Maker Witi board"
#define BOARD_VENDOR_NAME	"MQ Maker"
#define BOARD_VENDOR_URL	"https://mqmaker.com/"
#define BOARD_MODEL_URL		"https://mqmaker.com/product/witi-board/"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120
#undef  BOARD_GPIO_BTN_RESET
#define BOARD_GPIO_BTN_WPS	18
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
//#define BOARD_GPIO_LED_POWER	25
//#define BOARD_GPIO_LED_LAN	24
//#define BOARD_GPIO_LED_WAN	23
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1
#define BOARD_USB_PORT_SWAP	0
